# Generated by Django 5.1.1 on 2024-10-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0018_likedreply_reply_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
    ]
